# Generated by Django 4.2.9 on 2024-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationInquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("num_adults", models.PositiveIntegerField()),
                ("num_children_0_3", models.PositiveIntegerField(default=0)),
                ("num_children_4_13", models.PositiveIntegerField(default=0)),
                ("num_animals", models.PositiveIntegerField(default=0)),
                (
                    "tent_type",
                    models.CharField(
                        blank=True,
                        choices=[("2p", "2-person tent"), ("3-4p", "3-4 person tent"), ("5-6p", "5-6 person tent")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("caravan_required", models.BooleanField(default=False)),
                ("electricity_for_tent", models.BooleanField(default=False)),
                ("electricity_for_caravan", models.BooleanField(default=False)),
                ("extra_person_count", models.PositiveIntegerField(default=0)),
                ("waste_disposal", models.BooleanField(default=False)),
                ("parking_required", models.BooleanField(default=False)),
                ("num_beach_stay_adults", models.PositiveIntegerField(default=0)),
                ("num_beach_stay_children", models.PositiveIntegerField(default=0)),
                ("apply_discount", models.BooleanField(default=False)),
                ("inquiry_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the stay has been confirmed by the camping site."
                    ),
                ),
                (
                    "is_canceled",
                    models.BooleanField(
                        default=False, help_text="Indicates if the reservation has been canceled by the user."
                    ),
                ),
            ],
        ),
    ]
