# Generated by Django 4.2.9 on 2024-09-08 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_reservationinquiry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservationinquiry",
            options={"verbose_name": "Rezerwacja", "verbose_name_plural": "Rezerwacje"},
        ),
        migrations.AddField(
            model_name="reservationinquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="apply_discount",
            field=models.BooleanField(default=False, verbose_name="Zastosuj zniżkę za pobyt powyżej 5 dni"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="caravan_required",
            field=models.BooleanField(default=False, verbose_name="Czy wymagana przyczepa/kamper"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="electricity_for_caravan",
            field=models.BooleanField(default=False, verbose_name="Prąd i sanitariaty dla przyczepy/kampera"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="electricity_for_tent",
            field=models.BooleanField(default=False, verbose_name="Prąd i sanitariaty dla namiotu"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="end_date",
            field=models.DateField(verbose_name="Data zakończenia"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="extra_person_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba dodatkowych osób"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Imię i nazwisko"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="inquiry_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data zapytania"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="is_canceled",
            field=models.BooleanField(
                default=False,
                help_text="Czy rezerwacja została anulowana przez użytkownika?",
                verbose_name="Anulowane",
            ),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, help_text="Czy pobyt został potwierdzony przez camping?", verbose_name="Potwierdzone"
            ),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_adults",
            field=models.PositiveIntegerField(verbose_name="Liczba dorosłych"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_animals",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba zwierząt"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_beach_stay_adults",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba dorosłych na plaży"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_beach_stay_children",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba dzieci na plaży"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_children_0_3",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba dzieci (0-3 lata)"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="num_children_4_13",
            field=models.PositiveIntegerField(default=0, verbose_name="Liczba dzieci (4-13 lat)"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="parking_required",
            field=models.BooleanField(default=False, verbose_name="Parking wymagany"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Numer telefonu"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="start_date",
            field=models.DateField(verbose_name="Data rozpoczęcia"),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="tent_type",
            field=models.CharField(
                blank=True,
                choices=[("2p", "Namiot 2-osobowy"), ("3-4p", "Namiot 3-4 osobowy"), ("5-6p", "Namiot 5-6 osobowy")],
                max_length=5,
                null=True,
                verbose_name="Rodzaj namiotu",
            ),
        ),
        migrations.AlterField(
            model_name="reservationinquiry",
            name="waste_disposal",
            field=models.BooleanField(default=False, verbose_name="Wywóz odpadów"),
        ),
    ]
